# Training configuration
GPU: [0]

VERBOSE: False

MODEL:
  MODE: 'MIT_5K'

# Optimization arguments.
OPTIM:
  BATCH: 8
  EPOCHS: 1000
  # EPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 10
  RESUME: False
  PATCH_SIZES: [128, 256, 384]
  BATCH_SIZES: [4, 2, 2]
  EPOCHS_PER_SIZE: [400, 400, 200]
  TRAIN_DIR: '/data/xr/Dataset/light_dataset/MIT-Adobe-5K-512/train'       # path to training data
  VAL_DIR: '/data/xr/Dataset/light_dataset/MIT-Adobe-5K-512/test' # path to validation data
  SAVE_DIR: './checkpoints/MIT_5K/'           # path to save models and images
