# Training configuration
GPU: [1]

VERBOSE: False

MODEL:
  MODE: 'SDSD_indoor'

# Optimization arguments.
OPTIM:
  # BATCH: 4 # 8
  # EPOCHS: 1000  #200
  # # EPOCH_DECAY: [10]
  # LR_INITIAL: 2e-4  # 1e-4
  # LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1  # 1
  RESUME: False   # False
  PATCH_SIZES: [256, 384, 512]
  BATCH_SIZES: [2, 2, 1]
  EPOCHS_PER_SIZE: [400, 400, 200]
  TRAIN_DIR: '/data/xr/Dataset/light_dataset/SDSD_indoor_png/train/'       # path to training data
  VAL_DIR: '/data/xr/Dataset/light_dataset/SDSD_indoor_png/eval/' # path to validation data
  SAVE_DIR: './checkpoints/SDSD_indoor/'           # path to save models and images
